### PR TITLE
Sync chromium 97.0.4692.71 toolchain

### PR DESCRIPTION
**Pull request by Kudo**
fix newer macos toolchain building issues.

this is a large pr but i tried to keeps each commits as meaningful as possible. hopefully to get review easier.

- since in the newer chromium libc++, they removed `filesystem` support. i turned to rewrite the code with linux system c functions. i may think to introduce chromium's [base libraries](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/base) to do the common stuffs in the future.
- the following custom change seems not be used, please let me know if we should keep this:
https://github.com/react-native-skia/react-native-skia/blob/f13c60f2986b4bb89a536f75a4b90c816cf8e18a/build/config/compiler/BUILD.gn#L1976-L1993

### CODE REVIEW

**Comment by Taym95** [comment]
build perfectly on macOS 🚀

**Comment by munezbn** [comment]
> Works perfectly on macOS 🚀

You mean with even the RN app with` rns_shell` ( with your initial changes )

**Comment by munezbn** [comment]
Hi @Kudo 

There around 5k+ files changed and Not able to load all the files and chrome is not able to scroll also.  Is it possible to split the PR with two parts where one change is for FOSS source ( Which we may not have to review) and then` ReactSkia`, `rns-shel`l and `build `config changes.

**Comment by Taym95** [comment]
> > Works perfectly on macOS 🚀
> 
> You mean with even the RN app with` rns_shell` ( with your initial changes )

sorry I meant, chromium built on macOS 12.1  now and I don't see build issues I faced before

**Comment by Kudo** [comment]
> There around 5k+ files changed and Not able to load all the files and chrome is not able to scroll also. Is it possible to split the PR with two parts where one change is for FOSS source ( Which we may not have to review) and then` ReactSkia`, `rns-shel`l and `build `config changes.

@munezbn  i am sorry to have this large pr. i think the best way to review is by commits. please click each commits in this view: https://github.com/react-native-skia/react-native-skia/pull/40/commits. for example: [this commit](https://github.com/react-native-skia/react-native-skia/pull/40/commits/f0ebf9882ddc7385b77fdb5c89d5fc3d50f43ea6) i had the commit message:
```
Sync tools

rm -rf tools && cp -R /path/to/chromium/src/tools .
````

**Comment by pprabhu-ng** [comment]
Apologizing for the late review. 
@munezbn have reviewed rns_shell , build/secondary changes . LGTM !!

**Review by pprabhu-ng — APPROVED** [review]

**Review by munezbn — APPROVED** [review]
Sorry for the delay.I have reviewed all the(manual)  changes expect changes caused by sync. LGTM
Hopefully will see MAC support back soon :)

**Pull request merged**
